// disneyMovies.js
export const disneyMovies = [
  {
    id: 1,
    title: "Snow White and the Seven Dwarfs",
    year: 1937,
    leadCharacters: ["Snow White", "The Evil Queen"],
    era: "Golden Age",
    rating: "G",
    runtimeMin: 83,
    poster: "https://picsum.photos/seed/snowwhite/300/450",
    synopsis:
      "A kind princess befriends seven dwarfs while fleeing a jealous queen.",
  },
  {
    id: 2,
    title: "Pinocchio",
    year: 1940,
    leadCharacters: ["Pinocchio", "Jiminy Cricket", "Geppetto"],
    era: "Golden Age",
    rating: "G",
    runtimeMin: 88,
    poster: "https://picsum.photos/seed/pinocchio/300/450",
    synopsis:
      "A wooden puppet must prove himself brave, truthful, and unselfish to become a real boy.",
  },
  {
    id: 3,
    title: "Fantasia",
    year: 1940,
    leadCharacters: ["Mickey Mouse (Sorcerer’s Apprentice)"],
    era: "Golden Age",
    rating: "G",
    runtimeMin: 126,
    poster: "https://picsum.photos/seed/fantasia/300/450",
    synopsis:
      "Animated segments set to classical music in an experimental anthology.",
  },
  {
    id: 4,
    title: "Cinderella",
    year: 1950,
    leadCharacters: ["Cinderella", "Fairy Godmother"],
    era: "Silver Age",
    rating: "G",
    runtimeMin: 74,
    poster: "https://picsum.photos/seed/cinderella/300/450",
    synopsis: "A mistreated girl finds magic and a way to the royal ball.",
  },
  {
    id: 5,
    title: "Sleeping Beauty",
    year: 1959,
    leadCharacters: ["Aurora", "Maleficent", "Prince Phillip"],
    era: "Silver Age",
    rating: "G",
    runtimeMin: 75,
    poster: "https://picsum.photos/seed/sleepingbeauty/300/450",
    synopsis: "A princess cursed to sleep is saved by true love’s kiss.",
  },
  {
    id: 6,
    title: "The Little Mermaid",
    year: 1989,
    leadCharacters: ["Ariel", "Prince Eric", "Ursula"],
    era: "Disney Renaissance",
    rating: "G",
    runtimeMin: 83,
    poster: "https://picsum.photos/seed/littlemermaid/300/450",
    synopsis: "A curious mermaid makes a deal to live on land and pursue love.",
  },
  {
    id: 7,
    title: "Beauty and the Beast",
    year: 1991,
    leadCharacters: ["Belle", "Beast", "Gaston"],
    era: "Disney Renaissance",
    rating: "G",
    runtimeMin: 84,
    poster: "https://picsum.photos/seed/beautybeast/300/450",
    synopsis: "A young woman discovers the humanity within a cursed prince.",
  },
  {
    id: 8,
    title: "Aladdin",
    year: 1992,
    leadCharacters: ["Aladdin", "Jasmine", "Genie", "Jafar"],
    era: "Disney Renaissance",
    rating: "G",
    runtimeMin: 90,
    poster: "https://picsum.photos/seed/aladdin/300/450",
    synopsis: "A street-smart hero finds a magic lamp and big possibilities.",
  },
  {
    id: 9,
    title: "The Lion King",
    year: 1994,
    leadCharacters: ["Simba", "Mufasa", "Scar", "Nala"],
    era: "Disney Renaissance",
    rating: "G",
    runtimeMin: 88,
    poster: "https://picsum.photos/seed/lionking/300/450",
    synopsis: "A young lion prince faces loss, exile, and his destiny.",
  },
  {
    id: 10,
    title: "Mulan",
    year: 1998,
    leadCharacters: ["Mulan", "Mushu", "Shang"],
    era: "Disney Renaissance",
    rating: "G",
    runtimeMin: 88,
    poster: "https://picsum.photos/seed/mulan/300/450",
    synopsis:
      "A brave young woman disguises herself to save her father and country.",
  },
  {
    id: 11,
    title: "Tarzan",
    year: 1999,
    leadCharacters: ["Tarzan", "Jane", "Kala"],
    era: "Disney Renaissance",
    rating: "G",
    runtimeMin: 88,
    poster: "https://picsum.photos/seed/tarzan/300/450",
    synopsis: "A man raised by apes grapples with identity and new love.",
  },
  {
    id: 12,
    title: "Lilo & Stitch",
    year: 2002,
    leadCharacters: ["Lilo", "Stitch", "Nani"],
    era: "Post-Renaissance",
    rating: "PG",
    runtimeMin: 85,
    poster: "https://picsum.photos/seed/lilostitch/300/450",
    synopsis: "A lonely girl adopts a chaotic alien and finds ohana.",
  },
  {
    id: 13,
    title: "Frozen",
    year: 2013,
    leadCharacters: ["Elsa", "Anna", "Olaf", "Kristoff"],
    era: "Revival",
    rating: "PG",
    runtimeMin: 102,
    poster: "https://picsum.photos/seed/frozen/300/450",
    synopsis: "Two sisters learn about love, fear, and letting go.",
  },
  {
    id: 14,
    title: "Moana",
    year: 2016,
    leadCharacters: ["Moana", "Maui"],
    era: "Revival",
    rating: "PG",
    runtimeMin: 107,
    poster: "https://picsum.photos/seed/moana/300/450",
    synopsis:
      "A wayfinder sails beyond the reef to restore the heart of Te Fiti.",
  },
  {
    id: 15,
    title: "Encanto",
    year: 2021,
    leadCharacters: ["Mirabel", "Abuela Alma", "Bruno"],
    era: "Revival",
    rating: "PG",
    runtimeMin: 102,
    poster: "https://picsum.photos/seed/encanto/300/450",
    synopsis:
      "In a magical family, one girl without a gift discovers how to save them all.",
  },
];
